#!/bin/bash

# make and change to a directory
md () { mkdir -p "$1" && cd "$1"; }

line () {
    cat $2 | head -$1 | tail -1
}

bw () {
    cat $3 | head -$2 | tail -`expr $2 - $1 + 1`
}

mkvirtenv() {
    [ "$#" -eq 1 ] && mkdir -p ~/.virtualenvs/$1 && virtualenv ~/.virtualenvs/$1
}

virtenv() {
    [ "$#" -eq 1 ] && source ~/.virtualenvs/$1/bin/activate
}

man() {
    env \
        LESS_TERMCAP_mb=$(printf "$EWHITE") \
        LESS_TERMCAP_md=$(printf "$EWHITE") \
        LESS_TERMCAP_me=$(printf "$NO_COLOR") \
        LESS_TERMCAP_se=$(printf "$NO_COLOR") \
        LESS_TERMCAP_so=$(printf "\e[1;47;30m") \
        LESS_TERMCAP_ue=$(printf "$NO_COLOR") \
        LESS_TERMCAP_us=$(printf "$CYAN") \
        man "$@"
}

syspip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}
