#!/bin/bash
# Ensure user-installed binaries take precedence
export PATH=$(pwd)/bin:/usr/local/bin:$PATH

# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"

# Add node, npm, nvm paths dynamicly
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Add rvm, rpm, gem paths dynamicly as first place in the path
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

export PATH=$PATH:/usr/local/opt/go/libexec/bin
