#!/bin/bash
export DOTFILES_DIR="$HOME/code/dotfiles"

export GRUNT_DEBUG=1
export MR_DEBUG=1
export MRUI_DEBUG=1

export NVM_DIR="$HOME/.nvm"
# nvm auto complete support
[[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion

export GOPATH="$HOME/code/go"
